DEFAULT_TAG_BEGIN = r"// %%"
DEFAULT_TAG_END = r"// \%%"

TAG_GENERATED = "<!-- generated by Unimacro -->"
TAG_EXEC = "!!"
TAG_PROCESS = "->"

TAG_EXEC_INLINE = "!"
TAG_CONTINUE = "> "
TAG_EVAL = "="
TAG_SKIP = "--"

MULTILINE_TAGS = [
    TAG_GENERATED,
    TAG_EXEC,
    TAG_PROCESS
]
